# Generated by Django 5.1.4 on 2025-01-10 17:46

import authentication.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=authentication.models.custom_upload_to, verbose_name='Avatar of user')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('fullName', models.CharField(max_length=100, verbose_name='Full name of user')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter Profile')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook Profile')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Profile')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
